### ISSUE TITLE
Scroll intero schermo

### ISSUE THREAD

**Issue by mancusoa74** [ittagnelli/snAcks#10]
rimuovere lo scroll dell'intero schermo tramite CSS

**Comment by mancusoa74** [comment]
fixed

**Comment by Andrea-Canale** [comment]
https://stackoverflow.com/questions/28411499/disable-scrolling-on-body
Da stackoverflow: position: fixed; (this worked, but it scrolled completely to the top, which is unacceptable for this specific application).
Probabilmente è il nostro caso.
Proviamo con questo:

```css
html, body {margin: 0; height: 100%; overflow: hidden}
```
